name: C++ CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        DEPS_FILE="https://raw.githubusercontent.com/userver-framework/userver/refs/heads/develop/scripts/docs/en/deps/${{matrix.os}}.md"
        sudo apt update
        sudo apt install --allow-downgrades -y $(wget -q -O - ${DEPS_FILE})
        sudo apt install -y libboost-all-dev
        python3 -m pip install -r requirements.txt

    - name: Cache build directory
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build the project
      run: |
        cd build
        make
