name: C++ CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y cmake g++ libssl-dev libboost-all-dev libyaml-cpp-dev libjemalloc-dev libnghttp2-dev libev-dev libre2-dev
        python3 -m pip install -r requirements.txt
    
    - name : Install re2 from source
      run |
        sudo apt install -y git build-essential cmake
        git clone https://github.com/google/re2.git
        cd re2
        make
        sudo make install

    - name: Cache build directory
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build the project
      run: |
        cd build
        make
